### ISSUE TITLE
game_of_life.md

### ISSUE THREAD

**Issue by tinycrops** [jasonjmcghee/mdxish#2]
doesn't load.  something to do with WebGPU failing to load.

naive-gi.md and falling-sand.md both are fine.

**Comment by jasonjmcghee** [comment]
This is expected behavior.

If you're browser doesn't support WebGPU it can't run WebGPU.

Currently only chromium based browsers support WebGPU on non-nightly builds.

---

Let me know if I'm misunderstanding something- happy to reopen.
